using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using EquityTrading.Client.Utils;

namespace EquityTrading.Client.Models
{
    public class Order
    {
        public OrderType Type { get; set; }

        [HideColumnIfAutoGenerated()]
        public string UserId { get; set; }
        public string UserName { get; set; }
        public string Symbol { get; set; }
        public int Quantity { get; set; }
        public int ExecQty { get; set; }
        public int BalQty { get; set; }
        public double Price { get; set; }
        public DateTime Placed_Time { get; set; }

        [HideColumnIfAutoGenerated()]
        public DateTime Executed_Time { get; set; }
        public OrderStatus Status { get; set; }
    }
    public enum OrderType { BUY, SELL }
    public enum OrderStatus { OPEN, EXECUTED, CANCELLED, PARTIAL }
}
